export const SCAN_INIT = "SCAN_INIT";
export const SCAN_SUCCESS = "SCAN_SUCCESS";
export const SCAN_FAILURE = "SCAN_FAILURE";

export const PORTFOLIO_INIT = "PORTFOLIO_INI";
export const PORTFOLIO_SUCCESS = "PORTFOLIO_SUCCESS";
export const PORTFOLIO_FAILURE = "PORTFOLIO_FAILURE";

export const RETURNS_INIT = "RETURNS_INIT";
export const RETURNS_SUCESS = "RETURNS_SUCESS";
export const RETURNS_FAILURE = "RETURNS_FAILURE";

export const WATCHLIST_ADD = "WATCHLIST_ADD";
export const WATCHLIST_SUCCESS = "WATCHLIST_SUCCESS";
export const WATCHLIST_FAILURE = "WATCHLIST_FAILURE";
export const WATCHLIST_REMOVE = "WATCHLIST_REMOVE";
export const WATCHLIST_INIT_SUCCESS = "WATCHLIST_INIT_SUCCESS";
export const WATCHLIST_INIT_FAILURE = "WATCHLIST_INIT_FAILURE";
export const WATCHLIST_AUTOUPDATE_SUCCESS = "WATCHLIST_AUTOUPDATE_SUCCESS";
export const WATCHLIST_AUTOUPDATE_FAILURE = "WATCHLIST_AUTOUPDATE_FAILURE";
export const WATCHLIST_SET_TARGET_INIT = "WATCHLIST_SET_TARGET_INIT";
export const WATCHLIST_SET_TARGET_SUCCESS = "WATCHLIST_SET_TARGET_SUCCESS";
export const WATCHLIST_SET_TARGET_FAILURE = "WATCHLIST_SET_TARGET_FAILURE";

export const ANALYSIS_INIT = "ANALYSIS_INIT";
export const ANALYSIS_SUCCESS = "ANALYSIS_SUCCESS";
export const ANALYSIS_FAILURE = "ANALYSIS_FAILURE";
export const ANALYSIS_CLEAR = "ANALYSIS_CLEAR";
