export const SCAN_INIT = "SCAN_INIT";
export const SCAN_SUCCESS = "SCAN_SUCCESS";
export const SCAN_FAILURE = "SCAN_FAILURE";

export const PORTFOLIO_INIT = "PORTFOLIO_INI";
export const PORTFOLIO_SUCCESS = "PORTFOLIO_SUCCESS";
export const PORTFOLIO_FAILURE = "PORTFOLIO_FAILURE";
